/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksheetRouteImport } from './routes/worksheet'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IonsRouteImport } from './routes/ions'
import { Route as IndexRouteImport } from './routes/index'

const WorksheetRoute = WorksheetRouteImport.update({
  id: '/worksheet',
  path: '/worksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IonsRoute = IonsRouteImport.update({
  id: '/ions',
  path: '/ions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ions': typeof IonsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/worksheet': typeof WorksheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ions': typeof IonsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/worksheet': typeof WorksheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ions': typeof IonsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/worksheet': typeof WorksheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ions' | '/settings' | '/tools' | '/worksheet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ions' | '/settings' | '/tools' | '/worksheet'
  id: '__root__' | '/' | '/ions' | '/settings' | '/tools' | '/worksheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IonsRoute: typeof IonsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  WorksheetRoute: typeof WorksheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worksheet': {
      id: '/worksheet'
      path: '/worksheet'
      fullPath: '/worksheet'
      preLoaderRoute: typeof WorksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ions': {
      id: '/ions'
      path: '/ions'
      fullPath: '/ions'
      preLoaderRoute: typeof IonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IonsRoute: IonsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  WorksheetRoute: WorksheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
